### PR TITLE
Full content on source code page

### PR DESCRIPTION
**Pull request by Suryansh1720001**
## Fixes Issue

#54 

## Changes proposed

I added the gap between the source code button and the content in the Hindi navigation view. 
✅ Now the application working fine with both English and Hindi language.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] Remove the Bug of the source code dialog box. 

## Note to reviewers

Kindly check this and merge accordingly under IWOC ( IWOC + medium level) label.

### CODE REVIEW

**Comment by AyushAgnihotri2025** [comment]
Hey @Suryansh1720001,
Now also the full content is not visible (i.e.  **की है।** is still not visible) so, kindly fix it. And I think rather than decreasing the bottom margin of the button I will be great if you increase the height of the popup.

**Comment by Suryansh1720001** [comment]
Oh yeah, I just noticed. Sorry for that, I will change it asap.

**Comment by Suryansh1720001** [comment]
Hey, @AyushAgnihotri2025 

## Now check the pop-up dialog, it is working fine with both Hindi and English language.

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work 👍 @Suryansh1720001, Keep It Up.

**Pull request merged**
