### PR TITLE
hamburger color fix

### LINKED ISSUE #27: Incorrect Hamburger Menu color in Dark Mode
### What happened?

The Hamburger menu color isn't matching with the dark theme. It should be fixed.

### Reproduction steps

```bash
Steps to reproduce the behavior:

1. Open app
2. Click on theme toggle button
3. Switch to dark theme
4. See the unmatchable hamburger menu color in it.
```

### Expected behavior

It should have a matching color with the theme.

### Screenshots

217608036-7634e2b3-56e7-445f-af68-4eade396daa8

### Version

1.1.0 (Default)

### Version (If not available above)

_No response_

### What devices are you seeing the problem on?

Mobile, Tablet

### Device Name, Android Version and Screen Size

Every Device

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ksh1710**
## Fixes Issue
closes #27 

## Changes proposed
fixed the hamburger color issue in dark mode.....also, that saved instances part of the code was crashing the app therefore I commented it out.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
img1
img2

### CODE REVIEW

**Comment by ashupandey1620** [comment]
Nice Work @ksh1710.
But you haven't fixed the color issue in dark mode in inner Activity.
Kindly do it too.
calculatorErrorDark

**Comment by ksh1710** [comment]
@ashupandey1620 okk ya sure... I'll do it by today and update it. Sorry for the inconvenience.

**Comment by ksh1710** [comment]
hey @ashupandey1620 @AyushAgnihotri2025, I did the necessary changes, please review them and if any error occurs please let me know 
correction

**Comment by ashupandey1620** [comment]
Nice work @ksh1710, Keep it up.

**Pull request merged**
