### PR TITLE
Added different ln and log button , showing operands and operator

### PR DESCRIPTION
**Pull request by TheNPDev**
## Fixes Issue

#47 
#48

## Changes proposed

- Added different ln and log operator button
- Changes the UI according to the new button
- Added a new section of additional operator
- Now, operands and operator is showing on the screen 

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.
- [X] This PR does not contain plagiarized content.
- [X] The title of my pull request is a short description of the requested changes.

## Screenshots

WhatsApp Image 2023-02-25 at 6 52 28 PM

### CODE REVIEW

**Comment by TheNPDev** [comment]
Hey @AyushAgnihotri2025 , Please review my changes and merge it. Thanks

**Comment by AyushAgnihotri2025** [comment]
As I have mentioned here https://github.com/AyushAgnihotri2025/Calculator/issues/50#issuecomment-1445153105 so, I will review it by tomorrow and will further respond accordingly.

**Comment by TheNPDev** [comment]
Please also check the work done for issue #48 also and then decide its label accordingly,

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work 👍 @TheNPDev , Keep It Up.

**Pull request merged**
