### PR TITLE
Updated status bar color.

### PR DESCRIPTION
**Pull request by dhruv-porwal**
Now it should look transparent

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

221897246-919cb36d-9bb9-42e5-86fd-0a548a3c771e

### CODE REVIEW

**Comment by dhruv-porwal** [comment]
Sir please merge it.

**Comment by dhruv-porwal** [comment]
@AyushAgnihotri2025 sir please merge this one also.

**Comment by AyushAgnihotri2025** [comment]
Kindly add the screenshot of the changes

**Comment by dhruv-porwal** [comment]
Ok

**Comment by dhruv-porwal** [comment]
Now sir pls merge it.

**Review by AyushAgnihotri2025 — APPROVED** [review]
Great work @dhruv-porwal. Keep up the good work 👍

**Comment by dhruv-porwal** [comment]
Thank you sir 🙏 ☺️

**Pull request merged**
