### PR TITLE
Add on click satisfactory sound on functional keys

### PR DESCRIPTION
**Pull request by Suryansh1720001**
This is the PR of issue #8

## Changes proposed

✅ Add sound for satisfaction 📳
✅ Change vibration level to feel good with added sound 🔊

## Check List (Check all the applicable boxes) 

- ✅ My code follows the code style of this project.
- ✅ All new and existing tests passed.
- ✅ This PR does not contain plagiarized content.
- ✅ The title of my pull request is a short description of the requested changes.

## Screenshots
.

## Note :
@AyushAgnihotri2025 
This sound is only used for the buttons shown in the images. If you want me to add this sound to the operator and numeric buttons as well, let me know, and I'll do the same.

### CODE REVIEW

**Comment by AyushAgnihotri2025** [comment]
Hey @Suryansh1720001, 

I think it would be great if you add the sound 🔊 functionality in the `Clear` and `Equal` button too.

**Comment by Suryansh1720001** [comment]
Alright!

**Comment by Suryansh1720001** [comment]
Hello @AyushAgnihotri2025,
I added the functionality of sound on both the **Equal** and **Clear** Buttons.
You can check it as admin and merge it accordingly.
Thank you

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work 👍 @Suryansh1720001 , Keep It Up.

**Comment by Suryansh1720001** [comment]
Hello @AyushAgnihotri2025 
Thanks for your feedback.
Let's connect ->
GitHub -> @Suryansh1720001 (Follow)
LinkedIn -> https://www.linkedin.com/in/suryanshprajapati17

**Pull request merged**
