### PR TITLE
made the necessary UI enhancements and made dark mode access convenient

### LINKED ISSUE #1: Look Enhancement
### Is your feature request related to a problem? Please describe.

It's look has to be more enhanced.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ksh1710**
## Fixes Issue
closes #1 

## Changes proposed
gave the dark mode toggle on the main screen instead of the menu to make easy access for the user 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

imglight
imgdark
drawer

## Note to reviewers

made the dark theme a little better but the shadow of the buttons can still be worked upon which I wasn't able to resolve.

### CODE REVIEW

**Comment by AyushAgnihotri2025** [comment]
Hey @ksh1710,
Kindly include the screenshots of the changes you have made in the app along with your pull.

**Comment by ksh1710** [comment]
@AyushAgnihotri2025 uploaded the relevant images.

**Comment by AyushAgnihotri2025** [comment]
Nice work 👍  @ksh1710, we are reviewing your changes and will once merge when it's done.

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work 👍 @ksh1710 , Keep It Up.

**Comment by AyushAgnihotri2025** [comment]
Hey @ksh1710,
Kindly also update the color of this hamburger menu also in the dark mode. If you are doing this then kindly let me know.

216830423-75cfc1eb-7648-416a-b63b-dca0feaffe6e

**Pull request merged**
