### PR TITLE
Version Name added in Toast 

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Referring the Issue - #42 

## Fixes Issue

🪲 BUG like situation appear when we click on app version option and any type of action is not performed.

## Changes proposed

Added the Toast in version name - when we click on the app version option in the Navigation view.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work 👍 @Suryansh1720001 , Keep It Up.

**Comment by Suryansh1720001** [comment]
@AyushAgnihotri2025 
Thank you, Aayush. But I want to say something - you added the hard label here that was because I said it before or maybe this work deserves this. But in the issue of this PR, you added the label medium. So, Can you do that issue's label hard also?
So that it will be counted as in hard difficulty level.

**Comment by Suryansh1720001** [comment]
@AyushAgnihotri2025 
Kindly check the above message

**Comment by AyushAgnihotri2025** [comment]
> @AyushAgnihotri2025 Thank you, Aayush. But I want to say something - you added the hard label here that was because I said it before or maybe this work deserves this. But in the issue of this PR, you added the label medium. So, Can you do that issue's label hard also? So that it will be counted as in hard difficulty level.

Done 👍

**Pull request merged**
