### PR TITLE
updated readme images

### LINKED ISSUE #24: Add Version Control over different version of Android.
### Is your feature request related to a problem? Please describe.

Like for many devices it gives it a scroll view which doesn't looks good. So, Version Control should be added for different version of Android.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #25: Update README images according to app current version.
### Is your feature request related to a problem? Please describe.

README is using the old images of app.

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ksh1710**
## Fixes Issue
closes #25 
closes #24 

## Changes proposed
-->updated the images in readme according to the app's current version.
-->fixed the issue of the screen getting scrollable on smaller devices and unfit on larger screens.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots
final69

## Android 8
andr8
andr8dark

## Android 9
andr9Dark

andr9Light

## Android 11
andr11light

andr11Dark

## Android 12
andr12Dark
andr12Light

## Android 13

andr13Dark
andr13Light

### CODE REVIEW

**Comment by ksh1710** [comment]
hey @ashupandey1620 @AyushAgnihotri2025 , please look over the changes I made and do the needful

**Comment by ashupandey1620** [comment]
Images are not Loading in your readme fork @ksh1710 .........kindly rectify it.
RECTIFY

**Comment by ksh1710** [comment]
Ok @ashupandey1620 I'll check it out

**Comment by ksh1710** [comment]
Hey @ashupandey1620 can u please recheck if the images are visible or not...as here at my end and my other devies end there's no issue...please let me know the situation at your end then i ll look over it 
https://photos.app.goo.gl/zevPzdTZ6heqRkgG6


https://photos.app.goo.gl/va5aXn3aZwNh8K2S6

**Comment by ashupandey1620** [comment]
Hey @ksh1710 
In the below image, you have change the image path from link to assets folder path. 
rectify2

But in this case, the images will be shown to only those users who will be having the forked version of the Repository with all the updated commits and not to the other people.......... that's the reason you are able to see it in your read.me and others are not.
You can upload the image somewhere and then can use the link to fetch them for now.

@AyushAgnihotri2025 can change the link later.

**Comment by ksh1710** [comment]
Ok @ashupandey1620 I'll make the corrections

**Comment by ksh1710** [comment]
hey @ashupandey1620 please review the changes

**Review by AyushAgnihotri2025 — APPROVED** [review]
Nice work @ksh1710, Keep up the good work 👍

**Pull request merged**
